# Generated by Django 2.1.5 on 2019-10-09 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=256)),
                ('destination', models.CharField(max_length=256)),
                ('time', models.DateTimeField()),
                ('amount', models.FloatField()),
            ],
        ),
    ]
