# Generated by Django 2.1.11 on 2019-11-07 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lbcflba', '0003_auto_20191107_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='categoryDict',
            field=models.TextField(default='{}'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='category',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
