# Generated by Django 2.1.5 on 2020-01-17 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lbcflba', '0005_transaction_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='name',
            field=models.TextField(default='unnamed group'),
        ),
    ]
