# Generated by Django 2.1.5 on 2020-01-17 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lbcflba', '0006_group_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='spender',
            name='name',
            field=models.TextField(default='noname'),
        ),
    ]
