# Generated by Django 2.1.5 on 2020-01-18 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lbcflba', '0007_spender_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='destination',
            new_name='group',
        ),
    ]
