# Generated by Django 2.1.5 on 2020-01-18 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lbcflba', '0008_auto_20200118_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='destination',
            field=models.TextField(default='{}'),
        ),
    ]
