# Generated by Django 2.1.5 on 2019-10-09 07:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(default='', max_length=256)),
                ('time_start', models.DateTimeField(default=datetime.date(2000, 1, 1))),
                ('time_end', models.DateTimeField(default=datetime.date(2000, 1, 1))),
            ],
        ),
    ]
